spring.application.name=jwt-auth-service
# PostgreSQL Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_demo
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA Config (Hibernate handles table creation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# App-specific variables (Generate a long, strong secret key!)
jwt.secret=======================YourSuperSecretKeyForJwtSigningGoesHereMakeItLong=======================
jwt.expirationMs=86400000